swagger: "2.0"
info:
  description: "This is API documentation of CookIt."
  version: "1.0.0"
  title: "CookIt"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "daniorocket@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/api"
tags:
- name: "user"
  description: "Endpoints for user model."
- name: "recipe"
  description: "Endpoints for recipe model."
- name: "category"
  description: "Endpoints for category model."
schemes:
- "https"
- "http"
paths:
  /v1/register:
      post:
        tags:
        - "user"
        summary: "Add user account"
        description: ""
        operationId: "register"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: "User email, name and password."
          required: true
          schema:
            $ref: "#/definitions/Register"
        responses:
          "201":
            description: "Created user account"
          "400":
            description: "Invalid input"
  /v1/login:
      post:
        tags:
        - "user"
        summary: "Login"
        description: ""
        operationId: "login"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: "User email, name and password."
          required: true
          schema:
            $ref: "#/definitions/Login"
        responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/Token"
          "400":
            description: "Invalid username supplied"
          "404":
            description: "User not found"
  /v1/renew:
    get:
        tags:
        - "user"
        summary: "Renew JWT"
        description: "This method renew JWT.Require Authorization header with JWT. Example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbmlvcm9ja2V0IiwiZXhwIjoxNjI1NDAxMTAxfQ.vwmPuhoIv1KwcBaq534kp-YJiSm6xcQXtQte1Ssotbs"
        operationId: "renew"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: "User email, name and password."
          required: true
          schema:
            $ref: "#/definitions/Login"
        responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/Token"
          "500":
            description: "Invalid token or user credientals"
        security:
        - token: []
  /v1/category:
      post:
        tags:
        - "category"
        summary: "Add category"
        description: "This method require json and file. File is coded into Base64 and stored in DB."
        operationId: "addcategory"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: "User email, name and password."
          required: true
          schema:
            $ref: "#/definitions/Category"
        responses:
          "200":
            description: "Created category"
          "500":
            description: "Error decode JSON"
          "400":
            description: "Bad request"
        security:
        - token: []
      get:
        tags:
        - "category"
        summary: "Get all categories"
        responses:
          "200":
            description: "successful operation"
            schema:
              type: "object"
              properties:
                data:
                  type: "array"
                  items:
                    $ref: '#/definitions/Category'
                limit:
                  type: "string"
                  example: "1"
                page:
                  type: "string"
                  example: "1"
                totalElements:
                  type: "string"
                  example: "2"
  /v1/category/{id}:
    get:
      tags:
      - "category"
      summary: "Get category by ID"
      description: "This method return single category object with passed ID."
      operationId: "getcategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "path"
          name: "id"
          required: true
          description: "ID should be UUIDV4 string"
          type: "string"
      responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/Category"
  /v1/recipes:
      post:
        tags:
        - "recipe"
        summary: "Add recipe"
        description: "This method allow to add recipe"
        operationId: "addrecipe"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/Recipe"
        responses:
          "200":
            description: "Successful operation"
          "400":
            description: "Bad request"
definitions:
  Register:
      type: "object"
      properties:
        email:
          type: "string"
        username:
          type: "string"
        password:
          type: "string"
  Login:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
  Token:
    type: "string"
  Category:
      type: "object"
      properties:
        id:
          type: "string"
        labelPL:
          type: "string"
        labelEN:
          type: "string"
        file:
          $ref: "#/definitions/File"
  File:
      type: "object"
      properties:
        encodedURL:
          type: "string"
        extension:
          type: "string"
  Recipe:
    type: "object"
    properties:
      name:
        type: "string"
      listOfSteps:
        type: "array"
        items:
          type: "string"
          example: "a"
      listOfCategories:
        type: "array"
        items:
          $ref: "#/definitions/Category"
      tags:
        type: integer
      description:
        type: "string"
securityDefinitions:
  token:
    type: "basic"